### ISSUE TITLE
Installer wishlist : add an option to choose formating or not swap partition

### ISSUE THREAD

**Issue by OuailleAimeScier** [NuTyX/nutyx#1]
As a multi-distributions user with a multiboot on my laptop, could we have an option in the installer to choose if we want or not formating the existing swap partition (to avoid accidentally modifying swap's uuid for my other OS).
Thanks in advance.

**Comment by tnut** [comment]
I can make that setup-nutyx check if it is necessary or not to format a swap partition

**Comment by OuailleAimeScier** [comment]
Nice, thanks TNut !
