### ISSUE TITLE
wrong fromiso initialisation in init.in

### ISSUE THREAD

**Issue by guy2009** [NuTyX/nutyx#3]
A partir de la version "first try of live", et dans les versions suivantes,
le fichier init.in initialise la variable fromiso
   à "yes" 
   au lieu de ${param#fromiso=}

Du coup, il n'est plus possible de booter l'iso en loopback
comme proposé dans mon post "à propos de l'initrd"
(http://forum.nutyx.or/index.php?topic=280.msg1431#msg1431)

Cette erreur a été aussi introduite dans l'iso NuTyX_x86_64-20170625.iso.

**Comment by tnut** [comment]
Oups, je corrige cela pour la prochaine version super cool de m'avoir fait un  retour. Merci
